### ISSUE TITLE
sambamba-view: Error reading BGZF block starting from offset xxx: wrong BGZF magic

### ISSUE THREAD

**Issue by mortunco** [lomereiter/sambamba#212]
Hi,

I am using a pipeline called bcbio which your software was implemented in. During the process, I have obtained the following error which was told to be intermittent and filesystem related. Actually, I dont know how to describe the problem, because I dont know which part actually matters you. Therefore, I posted my error to you (I apologise).

```
sambamba-view: Error reading BGZF block starting from offset 145856923686: wrong BGZF magic
```

After I checked the problematic command, I realised that command itself does not create an error. The error was created when system tries to write to output or does something with it. I tried to ``` | grep ``` and it gave the same error.(forgive my non computational language)

The command that creates problem upon the output was written to some file.
```
/mnt/kufs/scratch/tmorova15/bcbio/galaxy/../anaconda/bin/sambamba view -F 'mapping_quality > 0' -L /mnt/kufs/scratch/tmorova15/ku_deneme_2/work/align/0c9a5dbc-f7f3-43e7-83d1-77b9fb4b8b54/PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc-callable-split/PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc-Y-callable-coverageregions.bed -f bam -l 1 /mnt/kufs/scratch/tmorova15/ku_deneme_2/work/align/0c9a5dbc-f7f3-43e7-83d1-77b9fb4b8b54/PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam | /mnt/kufs/scratch/tmorova15/bcbio/galaxy/../anaconda/bin/bedtools genomecov -split -ibam stdin -bga -g /mnt/kufs/scratch/tmorova15/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa.fai
```

The error that I get during the run.
```
[tmorova15@yunus log]$ cat bcbio-nextgen-debug.log 
[2016-05-15T15:17Z] System YAML configuration: /mnt/kufs/scratch/tmorova15/bcbio/galaxy/bcbio_system.yaml
[2016-05-15T15:17Z] Resource requests: sambamba, samtools; memory: 2.00, 2.00; cores: 16, 16
[2016-05-15T15:17Z] Configuring 1 jobs to run, using 8 cores each with 16.1g of memory reserved for each job
[2016-05-15T15:17Z] Timing: organize samples
[2016-05-15T15:17Z] multiprocessing: organize_samples
[2016-05-15T15:17Z] Using input YAML configuration: /mnt/kufs/scratch/tmorova15/ku_deneme_2/config/deneme10.yaml.txt
[2016-05-15T15:17Z] Checking sample YAML configuration: /mnt/kufs/scratch/tmorova15/ku_deneme_2/config/deneme10.yaml.txt
[2016-05-15T15:17Z] Testing minimum versions of installed programs
[2016-05-15T15:17Z] Timing: alignment preparation
[2016-05-15T15:17Z] multiprocessing: prep_align_inputs
[2016-05-15T15:17Z] multiprocessing: disambiguate_split
[2016-05-15T15:17Z] Timing: alignment
[2016-05-15T15:17Z] multiprocessing: process_alignment
[2016-05-15T15:17Z] Index BAM file: PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T15:24Z] Timing: callable regions
[2016-05-15T15:24Z] multiprocessing: prep_samples
[2016-05-15T15:24Z] multiprocessing: postprocess_alignment
[2016-05-15T15:24Z] Resource requests: ; memory: 1.00; cores: 1
[2016-05-15T15:24Z] Configuring 8 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-05-15T15:24Z] multiprocessing: calc_callable_loci
[2016-05-15T15:24Z] bedtools genomecov: 6 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T15:24Z] bedtools genomecov: 7 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T15:24Z] bedtools genomecov: 3 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T15:24Z] bedtools genomecov: 4 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T15:24Z] bedtools genomecov: 5 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T15:24Z] bedtools genomecov: 8 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T15:24Z] bedtools genomecov: 1 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T15:24Z] bedtools genomecov: 2 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:02Z] bedtools groupby coverage: 8 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:04Z] bedtools groupby coverage: 7 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:06Z] bedtools genomecov: 9 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:07Z] bedtools groupby coverage: 6 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:08Z] bedtools groupby coverage: 5 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:09Z] bedtools genomecov: 10 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:10Z] bedtools groupby coverage: 4 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:11Z] bedtools groupby coverage: 3 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:12Z] bedtools genomecov: 11 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:13Z] bedtools genomecov: 12 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:15Z] bedtools groupby coverage: 1 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:16Z] bedtools genomecov: 13 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:17Z] bedtools groupby coverage: 2 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:17Z] bedtools genomecov: 14 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:22Z] bedtools genomecov: 15 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:24Z] bedtools genomecov: 16 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:24Z] bedtools groupby coverage: 9 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:28Z] bedtools genomecov: 17 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:29Z] bedtools groupby coverage: 10 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:31Z] bedtools groupby coverage: 13 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:32Z] bedtools groupby coverage: 14 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:33Z] bedtools genomecov: 18 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:34Z] bedtools groupby coverage: 11 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:34Z] bedtools genomecov: 19 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:35Z] bedtools genomecov: 20 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:35Z] bedtools groupby coverage: 12 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:35Z] bedtools groupby coverage: 15 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:37Z] bedtools groupby coverage: 16 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:37Z] bedtools genomecov: 21 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:38Z] bedtools genomecov: 22 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:39Z] bedtools genomecov: X : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:39Z] bedtools genomecov: Y : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:40Z] bedtools groupby coverage: 17 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:41Z] bedtools groupby coverage: Y : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:41Z] bedtools genomecov: NC_007605 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:41Z] bedtools groupby coverage: NC_007605 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:41Z] bedtools genomecov: hs37d5 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:41Z] bedtools groupby coverage: hs37d5 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:43Z] bedtools groupby coverage: 19 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:43Z] bedtools groupby coverage: 22 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:43Z] bedtools groupby coverage: 21 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:44Z] bedtools groupby coverage: 20 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:45Z] bedtools groupby coverage: 18 : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:51Z] bedtools groupby coverage: X : PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e.bam
[2016-05-15T16:54Z] multiprocessing: combine_bed
[2016-05-15T16:54Z] Resource requests: ; memory: 1.00; cores: 1
[2016-05-15T16:54Z] Configuring 8 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-05-15T16:54Z] 112415c3-8cea-4608-9f55-c5714ac77390: Assigned coverage as 'genome' with 91.1% genome coverage and 0.0% offtarget coverage
[2016-05-15T17:00Z] Identify high coverage regions
[2016-05-15T17:00Z] Processing reference #1 (1)
[2016-05-15T17:05Z] Processing reference #2 (2)
[2016-05-15T17:11Z] Processing reference #3 (3)
[2016-05-15T17:15Z] Processing reference #4 (4)
[2016-05-15T17:19Z] Processing reference #5 (5)
[2016-05-15T17:23Z] Processing reference #6 (6)
[2016-05-15T17:27Z] Processing reference #7 (7)
[2016-05-15T17:30Z] Processing reference #8 (8)
[2016-05-15T17:34Z] Processing reference #9 (9)
[2016-05-15T17:36Z] Processing reference #10 (10)
[2016-05-15T17:39Z] Processing reference #11 (11)
[2016-05-15T17:42Z] Processing reference #12 (12)
[2016-05-15T17:45Z] Processing reference #13 (13)
[2016-05-15T17:47Z] Processing reference #14 (14)
[2016-05-15T17:49Z] Processing reference #15 (15)
[2016-05-15T17:51Z] Processing reference #16 (16)
[2016-05-15T17:53Z] Processing reference #17 (17)
[2016-05-15T17:55Z] Processing reference #18 (18)
[2016-05-15T17:57Z] Processing reference #19 (19)
[2016-05-15T17:58Z] Processing reference #20 (20)
[2016-05-15T17:59Z] Processing reference #21 (21)
[2016-05-15T18:00Z] Processing reference #22 (22)
[2016-05-15T18:01Z] Processing reference #23 (X)
[2016-05-15T18:03Z] Processing reference #24 (Y)
[2016-05-15T18:03Z] Processing reference #25 (MT)
[2016-05-15T18:03Z] Processing reference #26 (GL000207.1)
[2016-05-15T18:03Z] Processing reference #27 (GL000226.1)
[2016-05-15T18:03Z] Processing reference #28 (GL000229.1)
[2016-05-15T18:03Z] Processing reference #29 (GL000231.1)
[2016-05-15T18:03Z] Processing reference #30 (GL000210.1)
[2016-05-15T18:03Z] Processing reference #31 (GL000239.1)
[2016-05-15T18:03Z] Processing reference #32 (GL000235.1)
[2016-05-15T18:03Z] Processing reference #33 (GL000201.1)
[2016-05-15T18:03Z] Processing reference #34 (GL000247.1)
[2016-05-15T18:03Z] Processing reference #35 (GL000245.1)
[2016-05-15T18:03Z] Processing reference #36 (GL000197.1)
[2016-05-15T18:03Z] Processing reference #37 (GL000203.1)
[2016-05-15T18:03Z] Processing reference #38 (GL000246.1)
[2016-05-15T18:03Z] Processing reference #39 (GL000249.1)
[2016-05-15T18:03Z] Processing reference #40 (GL000196.1)
[2016-05-15T18:03Z] Processing reference #41 (GL000248.1)
[2016-05-15T18:03Z] Processing reference #42 (GL000244.1)
[2016-05-15T18:03Z] Processing reference #43 (GL000238.1)
[2016-05-15T18:03Z] Processing reference #44 (GL000202.1)
[2016-05-15T18:03Z] Processing reference #45 (GL000234.1)
[2016-05-15T18:03Z] Processing reference #46 (GL000232.1)
[2016-05-15T18:03Z] Processing reference #47 (GL000206.1)
[2016-05-15T18:03Z] Processing reference #48 (GL000240.1)
[2016-05-15T18:03Z] Processing reference #49 (GL000236.1)
[2016-05-15T18:03Z] Processing reference #50 (GL000241.1)
[2016-05-15T18:03Z] Processing reference #51 (GL000243.1)
[2016-05-15T18:03Z] Processing reference #52 (GL000242.1)
[2016-05-15T18:03Z] Processing reference #53 (GL000230.1)
[2016-05-15T18:03Z] Processing reference #54 (GL000237.1)
[2016-05-15T18:03Z] Processing reference #55 (GL000233.1)
[2016-05-15T18:03Z] Processing reference #56 (GL000204.1)
[2016-05-15T18:03Z] Processing reference #57 (GL000198.1)
[2016-05-15T18:03Z] Processing reference #58 (GL000208.1)
[2016-05-15T18:03Z] Processing reference #59 (GL000191.1)
[2016-05-15T18:03Z] Processing reference #60 (GL000227.1)
[2016-05-15T18:03Z] Processing reference #61 (GL000228.1)
[2016-05-15T18:03Z] Processing reference #62 (GL000214.1)
[2016-05-15T18:03Z] Processing reference #63 (GL000221.1)
[2016-05-15T18:03Z] Processing reference #64 (GL000209.1)
[2016-05-15T18:03Z] Processing reference #65 (GL000218.1)
[2016-05-15T18:03Z] Processing reference #66 (GL000220.1)
[2016-05-15T18:03Z] Processing reference #67 (GL000213.1)
[2016-05-15T18:03Z] Processing reference #68 (GL000211.1)
[2016-05-15T18:03Z] Processing reference #69 (GL000199.1)
[2016-05-15T18:03Z] Processing reference #70 (GL000217.1)
[2016-05-15T18:03Z] Processing reference #71 (GL000216.1)
[2016-05-15T18:03Z] Processing reference #72 (GL000215.1)
[2016-05-15T18:03Z] Processing reference #73 (GL000205.1)
[2016-05-15T18:03Z] Processing reference #74 (GL000219.1)
[2016-05-15T18:03Z] Processing reference #75 (GL000224.1)
[2016-05-15T18:03Z] Processing reference #76 (GL000223.1)
[2016-05-15T18:03Z] Processing reference #77 (GL000195.1)
[2016-05-15T18:03Z] Processing reference #78 (GL000212.1)
[2016-05-15T18:03Z] Processing reference #79 (GL000222.1)
[2016-05-15T18:03Z] Processing reference #80 (GL000200.1)
[2016-05-15T18:03Z] Processing reference #81 (GL000193.1)
[2016-05-15T18:03Z] Processing reference #82 (GL000194.1)
[2016-05-15T18:03Z] Processing reference #83 (GL000225.1)
[2016-05-15T18:03Z] Processing reference #84 (GL000192.1)
[2016-05-15T18:03Z] Processing reference #85 (NC_007605)
[2016-05-15T18:03Z] Processing reference #86 (hs37d5)
[2016-05-15T18:05Z] Clean up raw coverage file
[2016-05-15T18:05Z] Prepare cleaned BED file : 112415c3-8cea-4608-9f55-c5714ac77390
[2016-05-15T18:06Z] bgzip PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e-callable-callableblocks.bed
[2016-05-15T18:06Z] tabix index PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e-callable-callableblocks.bed.gz
[2016-05-15T18:06Z] Prepare merged BED file : 112415c3-8cea-4608-9f55-c5714ac77390
[2016-05-15T18:06Z] bgzip PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e-callable-callableblocks-merged.bed
[2016-05-15T18:06Z] tabix index PCAWG.2ef785e0-283d-430e-99d7-536a8a67c39e-callable-callableblocks-merged.bed.gz
[2016-05-15T18:06Z] Resource requests: ; memory: 1.00; cores: 1
[2016-05-15T18:06Z] Configuring 8 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-05-15T18:06Z] multiprocessing: calc_callable_loci
[2016-05-15T18:06Z] bedtools genomecov: 3 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T18:06Z] bedtools genomecov: 1 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T18:06Z] bedtools genomecov: 4 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T18:06Z] bedtools genomecov: 2 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T18:06Z] bedtools genomecov: 7 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T18:06Z] bedtools genomecov: 5 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T18:06Z] bedtools genomecov: 6 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T18:06Z] bedtools genomecov: 8 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T18:55Z] bedtools groupby coverage: 8 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T18:59Z] bedtools groupby coverage: 7 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:00Z] bedtools genomecov: 9 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:01Z] bedtools groupby coverage: 6 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:03Z] bedtools groupby coverage: 5 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:04Z] bedtools genomecov: 10 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:05Z] bedtools groupby coverage: 4 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:06Z] bedtools groupby coverage: 3 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:07Z] bedtools genomecov: 11 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:10Z] bedtools genomecov: 12 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:12Z] bedtools genomecov: 13 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:13Z] bedtools groupby coverage: 1 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:14Z] bedtools genomecov: 14 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:15Z] bedtools groupby coverage: 2 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:21Z] bedtools genomecov: 15 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:23Z] bedtools groupby coverage: 9 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:23Z] bedtools genomecov: 16 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:27Z] bedtools genomecov: 17 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:31Z] bedtools groupby coverage: 10 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:32Z] bedtools groupby coverage: 13 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:33Z] bedtools groupby coverage: 14 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:35Z] bedtools groupby coverage: 11 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:35Z] bedtools genomecov: 18 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:36Z] bedtools genomecov: 19 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:36Z] bedtools genomecov: 20 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:37Z] bedtools groupby coverage: 12 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:38Z] bedtools groupby coverage: 15 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:39Z] bedtools groupby coverage: 16 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:40Z] bedtools genomecov: 21 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:41Z] bedtools genomecov: 22 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:42Z] bedtools genomecov: X : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:42Z] bedtools genomecov: Y : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:43Z] bedtools groupby coverage: 17 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:43Z] sambamba-view: Error reading BGZF block starting from offset 145856923686: wrong BGZF magic
[2016-05-15T19:45Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/kufs/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/mnt/kufs/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /mnt/kufs/scratch/tmorova15/bcbio/galaxy/../anaconda/bin/sambamba view -F 'mapping_quality > 0' -L /mnt/kufs/scratch/tmorova15/ku_deneme_2/work/align/0c9a5dbc-f7f3-43e7-83d1-77b9fb4b8b54/PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc-callable-split/PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc-Y-callable-coverageregions.bed -f bam -l 1 /mnt/kufs/scratch/tmorova15/ku_deneme_2/work/align/0c9a5dbc-f7f3-43e7-83d1-77b9fb4b8b54/PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam | /mnt/kufs/scratch/tmorova15/bcbio/galaxy/../anaconda/bin/bedtools genomecov -split -ibam stdin -bga -g /mnt/kufs/scratch/tmorova15/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa.fai > /mnt/kufs/scratch/tmorova15/ku_deneme_2/work/align/0c9a5dbc-f7f3-43e7-83d1-77b9fb4b8b54/PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc-callable-split/tx/tmpY5uHKo/PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc-Y-callable-genomecov.bed
sambamba-view: Error reading BGZF block starting from offset 145856923686: wrong BGZF magic
' returned non-zero exit status 1
[2016-05-15T19:45Z] bedtools genomecov: NC_007605 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:45Z] bedtools groupby coverage: NC_007605 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:45Z] bedtools genomecov: hs37d5 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:45Z] bedtools groupby coverage: hs37d5 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:47Z] bedtools groupby coverage: 21 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:47Z] bedtools groupby coverage: 19 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:48Z] bedtools groupby coverage: 22 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:48Z] bedtools groupby coverage: 20 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:50Z] bedtools groupby coverage: 18 : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
[2016-05-15T19:58Z] bedtools groupby coverage: X : PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
```

This error is the only error between me and experimental result of my project. I would be more than glad if you have any information about this error.

Thank you for your help,

Best,
Tunc.

**Comment by mortunco** [comment]
No news? @lomereiter

**Comment by lomereiter** [comment]
Hi,

Do I understand correctly that this is the same issue as described in https://github.com/chapmanb/bcbio-nextgen/issues/1392? Your posts there clearly say that there is an issue with the BAM file in question as three different tools give an error.

**Comment by mortunco** [comment]
I would like to get a confirm from the developer of that algorithm.

**Comment by lomereiter** [comment]
Well, the confirmation in your case is three tools saying basically the same thing:
* sambamba: Error reading BGZF block starting from offset 145856923686
* biobambam2: `BgzfInflate::decompressBlock(): inflate failed`
* Picard: 
```Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: Read error; BinaryCodec in readmode; file: /mnt/kufs/scratch/tmorova15/ku_deneme_2/input/PCAWG.cb950391-e450-477c-9bb9-7c6699f764cc.bam
    at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:406)
    at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:380)```

Sorry but this file is definitely corrupted, so you absolutely need to re-download/regenerate it.
